"""Deterministic A2A skills over a capability report. No LLM is involved here."""
from __future__ import annotations

import hashlib
import json
import re
from typing import Any

from hcl_eval import UNKNOWN, evaluate

PLACEHOLDER = {"score": "<generated by Score>", "secret": "<from Kubernetes Secret>", "generated": "<generated>"}


def _entrypoints(report: dict[str, Any]) -> list[tuple[dict[str, Any], dict[str, Any] | None]]:
    pairs = []
    for capability in report["capabilities"]:
        entries = capability.get("score", {}).get("entrypoints") or [None]
        pairs.extend((capability, entry) for entry in entries)
    return pairs


def _source(parameter: dict[str, Any], entry: dict[str, Any] | None) -> dict[str, Any]:
    for source in parameter.get("score_sources", []):
        if entry and source["provisioner"] == entry["uri"]:
            return source
    return {"set_by": "developer", "score_param": parameter["terraform_variable"]} if entry is None else {"set_by": "missing"}


def _developer_params(capability: dict[str, Any], entry: dict[str, Any] | None) -> list[dict[str, Any]]:
    params = []
    for parameter in capability["parameters"]:
        source = _source(parameter, entry)
        if source["set_by"] == "developer":
            params.append({
                "name": source["score_param"],
                "terraform_variable": parameter["terraform_variable"],
                "type": parameter["type"],
                "default": source.get("default", parameter["terraform_default"]),
                **({"effect": parameter["effect"]} if parameter.get("effect") else {}),
            })
    return params


def _slug(value: str) -> str:
    return re.sub(r"[^a-z0-9]+", "_", value.lower()).strip("_")


def _json_schema_type(tf_type: str) -> str | None:
    base = tf_type.split("(")[0].strip()
    return {"string": "string", "number": "number", "bool": "boolean", "list": "array", "set": "array",
            "tuple": "array", "map": "object", "object": "object"}.get(base)


def tool_manifest(report: dict[str, Any], platform: str = "valueops", agent: str = "infra") -> dict[str, Any]:
    """Each Score capability as a discoverable tool whose inputSchema is the score.yaml params it accepts."""
    tools = []
    for capability, entry in _entrypoints(report):
        provider = _slug(entry["score_class"]) if entry else "terraform"
        name = f"provision_{_slug(entry['score_type'] if entry else capability['id'])}"
        by_variable = {p["terraform_variable"]: p for p in capability["parameters"]}
        properties: dict[str, Any] = {}
        required = []
        for param in _developer_params(capability, entry):
            variable = by_variable[param["terraform_variable"]]
            schema: dict[str, Any] = {}
            # Like Terraform, fall back to the default's type when the variable declares none.
            json_type = _json_schema_type(param["type"]) or {bool: "boolean", str: "string", int: "number",
                                                             float: "number", list: "array", dict: "object"}.get(
                type(param["default"]))
            if json_type:
                schema["type"] = json_type
            if description := param.get("effect") or variable.get("description"):
                schema["description"] = description
            if param["default"] is None:
                required.append(param["name"])
            else:
                schema["default"] = param["default"]
            properties[param["name"]] = schema
        tools.append({
            "agent": agent,
            "provider": provider,
            "name": name,
            "id": f"{agent}.{provider}.{name}",
            "description": capability.get("summary") or f"Provision {', '.join(capability['terraform']['resources'])}.",
            "inputSchema": {"type": "object", "properties": properties, "required": required,
                            "additionalProperties": False},
            # Creates real cloud resources; the same request again converges to the same state.
            "annotations": {"readOnlyHint": False, "destructiveHint": False, "idempotentHint": True,
                            "openWorldHint": True},
        })
    digest = hashlib.sha256(json.dumps(tools, sort_keys=True, separators=(",", ":")).encode()).hexdigest()
    return {"provider": platform, "discoveryMode": "agent-discovery-live", "manifestDigest": f"sha256:{digest}",
            "tools": tools}


def list_capabilities(report: dict[str, Any], detail: str = "summary") -> dict[str, Any]:
    """detail: "summary" (what can be deployed and how to request it), "detailed" (plus rules and caveats),
    or "full" (the raw crawl report). The tool-manifest format is tool_manifest()."""
    if detail == "full":
        return report
    items = []
    for capability, entry in _entrypoints(report):
        if detail == "summary":
            items.append({
                "capability": f"{entry['score_type']}.{entry['score_class']}" if entry else capability["id"],
                "summary": capability.get("summary"),
                "aws_service": capability.get("aws_service"),
                "params": [{k: p[k] for k in ("name", "default", "effect") if k in p}
                           for p in _developer_params(capability, entry)],
                "outputs": [o["name"] for o in (entry["outputs"] if entry else capability["outputs"])],
            })
            continue
        items.append({
            "capability_id": capability["id"],
            "score_type": entry["score_type"] if entry else None,
            "score_class": entry["score_class"] if entry else None,
            "summary": capability.get("summary"),
            "aws_service": capability.get("aws_service"),
            "terraform_resources": capability["terraform"]["resources"],
            "developer_params": _developer_params(capability, entry),
            "fixed_settings": capability["fixed_settings"],
            "conditional_behaviours": [
                {k: b[k] for k in ("attribute", "expression", "description") if b.get(k) is not None}
                for b in capability["conditional_behaviours"]
            ],
            "outputs": [o["name"] for o in (entry["outputs"] if entry else capability["outputs"])],
            "constraints": capability.get("constraints", []),
            **({"score_example": entry["example"]} if entry else {}),
        })
    return {"sources": report["sources"], "capabilities": items}


def _coerce(value: Any, tf_type: str) -> tuple[Any, str | None]:
    if tf_type == "bool":
        if isinstance(value, bool):
            return value, None
        if str(value).lower() in ("true", "false"):
            return str(value).lower() == "true", None
        return value, f"expected a boolean, got {value!r}"
    if tf_type == "number":
        try:
            return json.loads(str(value)), None
        except ValueError:
            return value, f"expected a number, got {value!r}"
    if tf_type == "string" and isinstance(value, (dict, list)):
        return value, f"expected a string, got {type(value).__name__}"
    return value, None


def _find(report: dict[str, Any], request: dict[str, Any]):
    wanted_type, wanted_class = request.get("score_type"), request.get("score_class")
    wanted_id = request.get("capability_id")
    for capability, entry in _entrypoints(report):
        if wanted_id and capability["id"] == wanted_id and (entry is None or not wanted_type):
            return capability, entry
        if entry and entry["score_type"] == wanted_type and (not wanted_class or entry["score_class"] == wanted_class):
            return capability, entry
    return None, None


def check_request(report: dict[str, Any], request: dict[str, Any]) -> dict[str, Any]:
    """Decide whether a Score resource request can be satisfied, and what it would actually get.

    request: {"score_type", "score_class"} or {"capability_id"},
             "params": {score param: value}, optional "expect": {resource attribute: value}.
    """
    capability, entry = _find(report, request)
    if capability is None:
        available = [
            f"{e['score_type']}.{e['score_class']}" if e else c["id"] for c, e in _entrypoints(report)
        ]
        return {"verdict": "unsupported", "issues": [
            {"field": "score_type", "problem": "No capability matches this request", "available": available}]}

    issues: list[dict[str, Any]] = []
    params = dict(request.get("params") or {})
    by_param = {}
    env: dict[str, Any] = {}
    applied_defaults: dict[str, Any] = {}
    for parameter in capability["parameters"]:
        name = parameter["terraform_variable"]
        source = _source(parameter, entry)
        set_by = source["set_by"]
        if set_by == "developer":
            by_param[source["score_param"]] = parameter
            value = params.pop(source["score_param"], None)
            if value is None:
                value = source.get("default", parameter["terraform_default"])
                if value is None and parameter["required"]:
                    issues.append({"field": source["score_param"], "problem": "required parameter is missing"})
                    continue
                applied_defaults[source["score_param"]] = value
            coerced, problem = _coerce(value, parameter["type"])
            if problem:
                issues.append({"field": source["score_param"], "problem": problem})
            env[name] = coerced
        elif set_by == "platform":
            env[name] = _coerce(source["value"], parameter["type"])[0]
        elif set_by in ("terraform_default", "missing"):
            env[name] = parameter["terraform_default"]
            if set_by == "missing":
                issues.append({"field": name, "problem": "required Terraform variable is not set by the "
                                                         "platform provisioner; the plan would fail"})
        else:
            env[name] = UNKNOWN

    for leftover, value in params.items():
        parameter = next((p for p in capability["parameters"] if p["terraform_variable"] == leftover), None)
        if parameter is None:
            issues.append({"field": leftover, "problem": "unknown parameter",
                           "allowed": sorted(by_param)})
        else:
            source = _source(parameter, entry)
            issues.append({"field": leftover, "problem": f"not settable from Score; set by {source['set_by']}",
                           **({"value": source["value"]} if "value" in source else {})})

    for parameter in capability["parameters"]:
        for rule in parameter.get("validations", []):
            if evaluate(rule, env, capability.get("locals", {})) is False:
                issues.append({"field": parameter["terraform_variable"], "problem": f"fails Terraform validation: {rule}"})

    locals_ = capability.get("locals", {})
    resolved: dict[str, Any] = {}
    for resource in capability.get("resource_attributes", []):
        for attr in resource["attributes"]:
            if attr["kind"] == "fixed":
                value = attr["value"]
            else:
                value = evaluate(attr["expression"], env, locals_)
                if value is UNKNOWN:
                    unknown_vars = [v for v in attr["variables"] if env.get(v, UNKNOWN) is UNKNOWN]
                    value = PLACEHOLDER.get(
                        next((_source(p, entry)["set_by"] for p in capability["parameters"]
                              if p["terraform_variable"] in unknown_vars), ""), "<computed at apply time>")
            resolved[f"{resource['address']}.{attr['attribute']}"] = value

    for attribute, wanted in (request.get("expect") or {}).items():
        matches = [key for key in resolved if key == attribute or key.endswith(f".{attribute}")]
        if not matches:
            issues.append({"field": f"expect.{attribute}", "problem": "this capability has no such attribute"})
            continue
        actual = resolved[matches[0]]
        if isinstance(actual, str) and actual.startswith("<"):
            issues.append({"field": f"expect.{attribute}", "problem": f"cannot be known before apply ({actual})"})
        elif actual != wanted and str(actual).lower() != str(wanted).lower():
            behaviour = next((b for b in capability["conditional_behaviours"] if matches[0].endswith(b["attribute"])), None)
            issues.append({
                "field": f"expect.{attribute}", "problem": f"would be {actual!r}, not {wanted!r}",
                **({"rule": behaviour["expression"]} if behaviour else {}),
                **({"explanation": behaviour["description"]} if behaviour and behaviour.get("description") else {}),
            })

    developer_params = {name: env[p["terraform_variable"]] for name, p in by_param.items()
                        if p["terraform_variable"] in env and env[p["terraform_variable"]] is not UNKNOWN}
    result = {
        "verdict": "rejected" if issues else "accepted",
        "capability_id": capability["id"],
        "issues": issues,
        "applied_defaults": applied_defaults,
        "resolved_attributes": resolved,
        "source_commit": report["sources"]["terraform_modules"]["commit"],
    }
    if entry:
        result["score_resource"] = {"type": entry["score_type"], "class": entry["score_class"], "params": developer_params}
    return result
