"""Deterministic A2A skills over a capability report. No LLM is involved here."""
from __future__ import annotations

import hashlib
import json
import re
from typing import Any

from hcl_eval import UNKNOWN, evaluate

PLACEHOLDER = {"score": "<generated by Score>", "secret": "<from Kubernetes Secret>", "generated": "<generated>"}


def _entrypoints(report: dict[str, Any]) -> list[tuple[dict[str, Any], dict[str, Any] | None]]:
    pairs = []
    for capability in report["capabilities"]:
        entries = capability.get("score", {}).get("entrypoints")
        if not entries and not capability["terraform"]["resources"]:
            continue  # a shared helper module (e.g. access-lists: only locals and outputs) is not a deployable capability
        entries = entries or [None]
        pairs.extend((capability, entry) for entry in entries)
    return pairs


def _source(parameter: dict[str, Any], entry: dict[str, Any] | None) -> dict[str, Any]:
    for source in parameter.get("score_sources", []):
        if entry and source["provisioner"] == entry["uri"]:
            return source
    return {"set_by": "developer", "score_param": parameter["terraform_variable"]} if entry is None else {"set_by": "missing"}


def _developer_params(capability: dict[str, Any], entry: dict[str, Any] | None) -> list[dict[str, Any]]:
    params = []
    for parameter in capability["parameters"]:
        source = _source(parameter, entry)
        if source["set_by"] == "developer":
            params.append({
                "name": source["score_param"],
                "terraform_variable": parameter["terraform_variable"],
                "type": parameter["type"],
                "default": source.get("default", parameter["terraform_default"]),
                **({"effect": parameter["effect"]} if parameter.get("effect") else {}),
            })
    return params


def _slug(value: str) -> str:
    return re.sub(r"[^a-z0-9]+", "_", value.lower()).strip("_")


def _json_schema_type(tf_type: str) -> str | None:
    base = tf_type.split("(")[0].strip()
    return {"string": "string", "number": "number", "bool": "boolean", "list": "array", "set": "array",
            "tuple": "array", "map": "object", "object": "object"}.get(base)


def _tool_name(capability: dict[str, Any], entry: dict[str, Any] | None) -> tuple[str, str]:
    provider = _slug(entry["score_class"]) if entry else "terraform"
    return provider, f"provision_{_slug(entry['score_type'] if entry else capability['id'])}"


WORKLOAD_SCHEMA = {"type": "string", "pattern": "^[a-z0-9]([a-z0-9-]{0,38}[a-z0-9])?$",
                   "description": "Score workload name (metadata.name): lowercase letters, digits and hyphens, "
                                  "2-40 characters. Requests for the same workload update its resource."}
IMAGE_SCHEMA = {"type": "string", "pattern": "^[A-Za-z0-9._/:@-]+$",
                "description": "Container image of the workload, e.g. nginx:latest."}
REGIONS = ["us-east-1", "us-east-2", "us-west-1", "us-west-2"]
# Values score-api's /cgi-bin/score accepts (its allowlists are lowercase and case-sensitive).
SCORE_API_ALLOWED = {
    "environment": ["dev", "staging", "uat", "dr", "prod"],
    "instance_class": ["db.t3.micro", "db.t3.small", "db.t3.medium", "db.t4g.micro", "db.t4g.small"],
    "region": REGIONS,
    "plane": ["resource", "dev", "observability", "integration", "security", "unspecified"],
}
STORAGE_GB_RANGE = (1, 20)
PLANES = SCORE_API_ALLOWED["plane"]
ENVIRONMENTS = SCORE_API_ALLOWED["environment"]

# Score types score-api can execute, and what each needs besides the crawled params.
#   endpoint: score-api CGI endpoint; fields: request fields that are not Score params;
#   allowed: lowercase allowlists enforced before the call.
SCORE_TYPES: dict[str, dict[str, Any]] = {
    "postgres": {"endpoint": "score", "fields": ["workload", "image"], "allowed": SCORE_API_ALLOWED},
    # EKS: the module's own variable validations cover region, CIDRs and node sizes.
    # "inputs": the only params a user supplies; every other provisioner param keeps its platform default and is
    # neither advertised nor accepted. "require": inputs that are required although the module gives them a default.
    # enable_network_access (score-api default true) also creates the bastion, load balancer controller, NGINX and
    # NLB in the same request, fed from the cluster's outputs; bastion_access_mode picks ssm or ssh for that bastion.
    "eks": {"endpoint": "eks", "fields": ["workload"],
            "allowed": {"environment": ENVIRONMENTS, "plane": PLANES, "bastion_access_mode": ["ssm", "ssh"],
                        "ingress_nlb_scheme": ["internet-facing", "internal"]},
            # ingress_nlb_scheme internal: a private NLB, reached through a tunnel to the bastion's forwarder
            # (the stack's ingress_tunnel_command output).
            "inputs": ["cluster_name", "aws_account_id", "region", "kubernetes_version", "environment",
                       "enable_network_access", "bastion_access_mode", "ingress_nlb_scheme"],
            # What score-api applies when the input is left out (the provisioner's own default differs so that
            # clusters requested before bundling keep their shape when re-rendered).
            "defaults": {"enable_network_access": True}},
    # SSM bastion into an EKS VPC, requested separately from the cluster; the module validates the rest.
    # public_subnet_id is needed only with bastion_access_mode "ssh"; ssh_key_name defaults to "platform-bastion".
    "network-access": {"endpoint": "network-access", "fields": ["workload"],
                       "allowed": {"environment": ENVIRONMENTS, "plane": PLANES, "bastion_access_mode": ["ssm", "ssh"]},
                       "inputs": ["name", "aws_account_id", "region", "environment", "cluster_name", "vpc_id", "vpc_cidr", "subnet_id",
                                  "cluster_security_group_id", "bastion_access_mode", "ssh_key_name", "public_subnet_id"],
                       "require": ["cluster_security_group_id"],
                       "when": {("bastion_access_mode", "ssh"): ["public_subnet_id"]}},
}
# The modules' own can(regex(...)) validations, checked before score-api and advertised as schema patterns so forms
# can validate too. Keep in step with score-tf-modules variables.tf.
_ID = "[0-9a-f]{8,17}$"
INPUT_PATTERNS = {
    "eks": {"cluster_name": "^[a-z][a-z0-9-]{1,26}[a-z0-9]$", "aws_account_id": "^[0-9]{12}$",
            "region": "^[a-z]{2}(-gov)?-[a-z]+-[0-9]$", "kubernetes_version": "^1[.][0-9]{2}$"},
    "network-access": {"name": "^[a-z][a-z0-9-]{1,38}[a-z0-9]$", "cluster_name": "^[a-z][a-z0-9-]{1,26}[a-z0-9]$",
                       "aws_account_id": "^[0-9]{12}$", "region": "^[a-z]{2}(-gov)?-[a-z]+-[0-9]$",
                       "vpc_id": "^vpc-" + _ID, "subnet_id": "^subnet-" + _ID, "public_subnet_id": "^subnet-" + _ID,
                       "cluster_security_group_id": "^sg-" + _ID,
                       "vpc_cidr": "^([0-9]{1,3}[.]){3}[0-9]{1,3}/([0-9]|[12][0-9]|3[0-2])$",
                       "ssh_key_name": "^[A-Za-z0-9._-]{1,255}$"},
}
# Status filters: the prefix of each capability's Terraform CR names.
CAPABILITIES = ["rds", "eks", "network-access"]
EXECUTABLE_SCORE_TYPES = set(SCORE_TYPES)
FIELD_SCHEMAS = {"workload": WORKLOAD_SCHEMA, "image": IMAGE_SCHEMA}


def _action_tools(agent: str) -> list[dict[str, Any]]:
    """score-api operations that are not derived from Terraform: rotating AWS credentials and deleting everything."""
    return [
        {
            "agent": agent, "provider": "score_api", "name": "update_aws_credentials",
            "id": f"{agent}.score_api.update_aws_credentials",
            "description": "Rotates the AWS credentials that Terraform uses to provision resources: writes them to "
                           "Vault and re-reconciles every live Terraform resource with the new credentials.",
            "inputSchema": {"type": "object", "properties": {
                "access_key_id": {"type": "string", "pattern": "^[A-Z0-9]{16,32}$",
                                  "description": "AWS access key ID."},
                "secret_access_key": {"type": "string", "description": "AWS secret access key."},
                "region": {"type": "string", "enum": REGIONS, "default": "us-east-1",
                           "description": "Default AWS region stored with the credentials."},
            }, "required": ["access_key_id", "secret_access_key"], "additionalProperties": False},
            "annotations": {"readOnlyHint": False, "destructiveHint": False, "idempotentHint": True,
                            "openWorldHint": True},
        },
        {
            "agent": agent, "provider": "score_api", "name": "delete_all_resources",
            "id": f"{agent}.score_api.delete_all_resources",
            "description": "Destroys everything provisioned through score-api: every RDS database, every EKS "
                           "cluster (with its VPC, node group and ingress load balancer) and every network-access "
                           "bastion. Removes the Terraform resources so terraform "
                           "destroy deletes them in AWS, and cleans up their Secrets. Without confirm it only reports "
                           "what would be deleted. Takes 5-20 minutes (EKS clusters keep destroying for ~15 minutes "
                           "after it returns); send it with returnImmediately and poll GetTask.",
            "inputSchema": {"type": "object", "properties": {
                "confirm": {"type": "string", "enum": ["DELETE-ALL"],
                            "description": 'Set to "DELETE-ALL" to delete. Leave it out for a dry run.'},
            }, "required": [], "additionalProperties": False},
            "annotations": {"readOnlyHint": False, "destructiveHint": True, "idempotentHint": True,
                            "openWorldHint": True},
        },
        {
            "agent": agent, "provider": "score_api", "name": "resource_status",
            "id": f"{agent}.score_api.resource_status",
            "description": "Reports provisioning progress right now, with no input: one overall verdict across "
                           "everything provisioned (overall.state in_progress | succeeded | failed | none; overall.done "
                           "true unless in progress; on failure overall.error names the resource, the step and why), "
                           "one verdict per request (a cluster and its bundled network access count as one), and per "
                           "resource its step (waiting for a dependency, planning, applying, rechecking, ...), "
                           "conditions, runner pod, log tail and events. Poll it after provision or delete-all until "
                           "overall.done; task results only describe the moment a call ended.",
            "inputSchema": {"type": "object", "properties": {}, "required": [], "additionalProperties": False},
            "annotations": {"readOnlyHint": True, "destructiveHint": False, "idempotentHint": True,
                            "openWorldHint": True},
        },
    ]


def tool_manifest(report: dict[str, Any], platform: str = "valueops", agent: str = "infra",
                  actions: bool = False, plane: str = "resource") -> dict[str, Any]:
    """Each Score capability as a discoverable tool whose inputSchema is the score.yaml params it accepts.

    actions: the agent can execute tools through score-api, so provision tools also take the workload and image,
    and the score-api operations are listed too.
    """
    tools = []
    for capability, entry in _entrypoints(report):
        provider, name = _tool_name(capability, entry)
        by_variable = {p["terraform_variable"]: p for p in capability["parameters"]}
        properties: dict[str, Any] = {}
        required = []
        for param in _developer_params(capability, entry):
            variable = by_variable[param["terraform_variable"]]
            schema: dict[str, Any] = {}
            # Like Terraform, fall back to the default's type when the variable declares none.
            json_type = _json_schema_type(param["type"]) or {bool: "boolean", str: "string", int: "number",
                                                             float: "number", list: "array", dict: "object"}.get(
                type(param["default"]))
            if json_type:
                schema["type"] = json_type
            if description := param.get("effect") or variable.get("description"):
                schema["description"] = description
            if param["default"] is None:
                required.append(param["name"])
            else:
                schema["default"] = param["default"]
            properties[param["name"]] = schema
        if actions and entry and entry["score_type"] in EXECUTABLE_SCORE_TYPES:
            spec = SCORE_TYPES[entry["score_type"]]
            if "inputs" in spec:
                properties = {k: v for k, v in properties.items() if k in spec["inputs"]}
                required = [r for r in required if r in spec["inputs"]] + [
                    r for r in spec.get("require", []) if r in properties and r not in required]
                for r in spec.get("require", []):
                    properties.get(r, {}).pop("default", None)
                for field, pattern in INPUT_PATTERNS.get(entry["score_type"], {}).items():
                    if field in properties:
                        properties[field] = {**properties[field], "pattern": pattern}
                for field, value in spec.get("defaults", {}).items():
                    if field in properties:
                        properties[field] = {**properties[field], "default": value}
            for field, allowed in spec["allowed"].items():
                if field in properties:
                    properties[field] = {**properties[field], "enum": allowed}
            properties = {**{f: FIELD_SCHEMAS[f] for f in spec["fields"]}, **properties}
            required = [*spec["fields"], *required]
        tools.append({
            "agent": agent,
            "provider": provider,
            "name": name,
            "id": f"{agent}.{provider}.{name}",
            "description": capability.get("summary") or f"Provision {', '.join(capability['terraform']['resources'])}.",
            "inputSchema": {"type": "object", "properties": properties, "required": required,
                            "additionalProperties": False},
            # Creates real cloud resources; the same request again converges to the same state.
            "annotations": {"readOnlyHint": False, "destructiveHint": False, "idempotentHint": True,
                            "openWorldHint": True},
        })
    if actions:
        tools.extend(_action_tools(agent))
    digest = hashlib.sha256(json.dumps(tools, sort_keys=True, separators=(",", ":")).encode()).hexdigest()
    return {"provider": platform, "discoveryMode": "agent-discovery-live", "manifestDigest": f"sha256:{digest}",
            "plane": plane,
            "tools": tools}


def list_capabilities(report: dict[str, Any], detail: str = "summary") -> dict[str, Any]:
    """detail: "summary" (what can be deployed and how to request it), "detailed" (plus rules and caveats),
    or "full" (the raw crawl report). The tool-manifest format is tool_manifest()."""
    if detail == "full":
        return report
    items = []
    for capability, entry in _entrypoints(report):
        if detail == "summary":
            items.append({
                "capability": f"{entry['score_type']}.{entry['score_class']}" if entry else capability["id"],
                "summary": capability.get("summary"),
                "aws_service": capability.get("aws_service"),
                "params": [{k: p[k] for k in ("name", "default", "effect") if k in p}
                           for p in _developer_params(capability, entry)],
                "outputs": [o["name"] for o in (entry["outputs"] if entry else capability["outputs"])],
            })
            continue
        items.append({
            "capability_id": capability["id"],
            "score_type": entry["score_type"] if entry else None,
            "score_class": entry["score_class"] if entry else None,
            "summary": capability.get("summary"),
            "aws_service": capability.get("aws_service"),
            "terraform_resources": capability["terraform"]["resources"],
            "developer_params": _developer_params(capability, entry),
            "fixed_settings": capability["fixed_settings"],
            "conditional_behaviours": [
                {k: b[k] for k in ("attribute", "expression", "description") if b.get(k) is not None}
                for b in capability["conditional_behaviours"]
            ],
            "outputs": [o["name"] for o in (entry["outputs"] if entry else capability["outputs"])],
            "constraints": capability.get("constraints", []),
            **({"score_example": entry["example"]} if entry else {}),
        })
    return {"sources": report["sources"], "capabilities": items}


def _coerce(value: Any, tf_type: str) -> tuple[Any, str | None]:
    if tf_type == "bool":
        if isinstance(value, bool):
            return value, None
        if str(value).lower() in ("true", "false"):
            return str(value).lower() == "true", None
        return value, f"expected a boolean, got {value!r}"
    if tf_type == "number":
        try:
            return json.loads(str(value)), None
        except ValueError:
            return value, f"expected a number, got {value!r}"
    if tf_type == "string" and isinstance(value, (dict, list)):
        return value, f"expected a string, got {type(value).__name__}"
    return value, None


def _find(report: dict[str, Any], request: dict[str, Any]):
    wanted_type, wanted_class = request.get("score_type"), request.get("score_class")
    wanted_id = request.get("capability_id")
    for capability, entry in _entrypoints(report):
        if wanted_id and capability["id"] == wanted_id and (entry is None or not wanted_type):
            return capability, entry
        if entry and entry["score_type"] == wanted_type and (not wanted_class or entry["score_class"] == wanted_class):
            return capability, entry
    return None, None


def check_request(report: dict[str, Any], request: dict[str, Any]) -> dict[str, Any]:
    """Decide whether a Score resource request can be satisfied, and what it would actually get.

    request: {"score_type", "score_class"} or {"capability_id"},
             "params": {score param: value}, optional "expect": {resource attribute: value}.
    """
    capability, entry = _find(report, request)
    if capability is None:
        available = [
            f"{e['score_type']}.{e['score_class']}" if e else c["id"] for c, e in _entrypoints(report)
        ]
        return {"verdict": "unsupported", "issues": [
            {"field": "score_type", "problem": "No capability matches this request", "available": available}]}

    issues: list[dict[str, Any]] = []
    params = dict(request.get("params") or {})
    by_param = {}
    env: dict[str, Any] = {}
    applied_defaults: dict[str, Any] = {}
    for parameter in capability["parameters"]:
        name = parameter["terraform_variable"]
        source = _source(parameter, entry)
        set_by = source["set_by"]
        if set_by == "developer":
            by_param[source["score_param"]] = parameter
            value = params.pop(source["score_param"], None)
            if value is None:
                value = source.get("default", parameter["terraform_default"])
                if value is None and parameter["required"]:
                    issues.append({"field": source["score_param"], "problem": "required parameter is missing"})
                    continue
                applied_defaults[source["score_param"]] = value
            coerced, problem = _coerce(value, parameter["type"])
            if problem:
                issues.append({"field": source["score_param"], "problem": problem})
            env[name] = coerced
        elif set_by == "platform":
            env[name] = _coerce(source["value"], parameter["type"])[0]
        elif set_by in ("terraform_default", "missing"):
            env[name] = parameter["terraform_default"]
            if set_by == "missing":
                issues.append({"field": name, "problem": "required Terraform variable is not set by the "
                                                         "platform provisioner; the plan would fail"})
        else:
            env[name] = UNKNOWN

    for leftover, value in params.items():
        parameter = next((p for p in capability["parameters"] if p["terraform_variable"] == leftover), None)
        if parameter is None:
            issues.append({"field": leftover, "problem": "unknown parameter",
                           "allowed": sorted(by_param)})
        else:
            source = _source(parameter, entry)
            issues.append({"field": leftover, "problem": f"not settable from Score; set by {source['set_by']}",
                           **({"value": source["value"]} if "value" in source else {})})

    for parameter in capability["parameters"]:
        for rule in parameter.get("validations", []):
            if evaluate(rule, env, capability.get("locals", {})) is False:
                issues.append({"field": parameter["terraform_variable"], "problem": f"fails Terraform validation: {rule}"})

    locals_ = capability.get("locals", {})
    resolved: dict[str, Any] = {}
    for resource in capability.get("resource_attributes", []):
        for attr in resource["attributes"]:
            if attr["kind"] == "fixed":
                value = attr["value"]
            else:
                value = evaluate(attr["expression"], env, locals_)
                if value is UNKNOWN:
                    unknown_vars = [v for v in attr["variables"] if env.get(v, UNKNOWN) is UNKNOWN]
                    value = PLACEHOLDER.get(
                        next((_source(p, entry)["set_by"] for p in capability["parameters"]
                              if p["terraform_variable"] in unknown_vars), ""), "<computed at apply time>")
            resolved[f"{resource['address']}.{attr['attribute']}"] = value

    for attribute, wanted in (request.get("expect") or {}).items():
        matches = [key for key in resolved if key == attribute or key.endswith(f".{attribute}")]
        if not matches:
            issues.append({"field": f"expect.{attribute}", "problem": "this capability has no such attribute"})
            continue
        actual = resolved[matches[0]]
        if isinstance(actual, str) and actual.startswith("<"):
            issues.append({"field": f"expect.{attribute}", "problem": f"cannot be known before apply ({actual})"})
        elif actual != wanted and str(actual).lower() != str(wanted).lower():
            behaviour = next((b for b in capability["conditional_behaviours"] if matches[0].endswith(b["attribute"])), None)
            issues.append({
                "field": f"expect.{attribute}", "problem": f"would be {actual!r}, not {wanted!r}",
                **({"rule": behaviour["expression"]} if behaviour else {}),
                **({"explanation": behaviour["description"]} if behaviour and behaviour.get("description") else {}),
            })

    developer_params = {name: env[p["terraform_variable"]] for name, p in by_param.items()
                        if p["terraform_variable"] in env and env[p["terraform_variable"]] is not UNKNOWN}
    result = {
        "verdict": "rejected" if issues else "accepted",
        "capability_id": capability["id"],
        "issues": issues,
        "applied_defaults": applied_defaults,
        "resolved_attributes": resolved,
        "source_commit": report["sources"]["terraform_modules"]["commit"],
    }
    if entry:
        result["score_resource"] = {"type": entry["score_type"], "class": entry["score_class"], "params": developer_params}
    return result


def prepare_provision(report: dict[str, Any], tool_id: str, arguments: dict[str, Any],
                      agent: str = "infra") -> dict[str, Any]:
    """Validate a provision tool call against the crawled capability before anything is sent to score-api.

    Returns {"verdict": "accepted", "workload", "image", "params"} with defaults filled in from the manifest, or
    {"verdict": "rejected" | "unsupported", "issues": [...]}.
    """
    for capability, entry in _entrypoints(report):
        provider, name = _tool_name(capability, entry)
        if f"{agent}.{provider}.{name}" == tool_id:
            break
    else:
        return {"verdict": "unsupported", "issues": [{"field": "tool", "problem": f"no tool {tool_id!r}"}]}
    if not entry or entry["score_type"] not in EXECUTABLE_SCORE_TYPES:
        return {"verdict": "unsupported", "issues": [
            {"field": "tool", "problem": f"{tool_id} is listed but score-api cannot provision it yet"}]}

    spec = SCORE_TYPES[entry["score_type"]]
    # Form fields often carry stray spaces ("subnet-0b89...  "); a trimmed value is what the user meant.
    arguments = {k: v.strip() if isinstance(v, str) else v for k, v in arguments.items()}
    fields = {f: arguments.pop(f, None) for f in spec["fields"]}
    issues = []
    for field, pattern in INPUT_PATTERNS.get(entry["score_type"], {}).items():
        value = arguments.get(field)
        if value not in (None, "") and not (isinstance(value, str) and re.match(pattern, value)):
            issues.append({"field": field, "problem": f"{value!r} must match {pattern}"})
    for (field, wanted), needed in spec.get("when", {}).items():
        if str(arguments.get(field, "")).lower() == wanted:
            issues += [{"field": n, "problem": f"required when {field} is {wanted!r}"}
                       for n in needed if not arguments.get(n)]
    if "inputs" in spec:
        issues += [{"field": k, "problem": "set by the platform; not a request input"}
                   for k in sorted(arguments) if k not in spec["inputs"]]
        issues += [{"field": r, "problem": "required"} for r in spec.get("require", []) if not arguments.get(r)]
    # Forms often send display labels ("Resource", "Dev"); score-api only accepts lowercase.
    for name, allowed in spec["allowed"].items():
        if isinstance(arguments.get(name), str):
            arguments[name] = arguments[name].strip().lower()
            if arguments[name] not in allowed:
                issues.append({"field": name, "problem": f"must be one of {allowed}"})
    # A JSON number loses trailing zeros (1.30 becomes 1.3), so versions must be strings.
    if "kubernetes_version" in arguments and not isinstance(arguments["kubernetes_version"], str):
        issues.append({"field": "kubernetes_version", "problem": 'must be a string such as "1.34"'})
    if entry["score_type"] == "postgres" and arguments.get("storage_gb") is not None:
        low, high = STORAGE_GB_RANGE
        try:
            size = float(arguments["storage_gb"])
        except (TypeError, ValueError):
            size = None
        if size is None or not size.is_integer() or not low <= size <= high:
            issues.append({"field": "storage_gb", "problem": f"must be a whole number from {low} to {high}"})
    for field, value in fields.items():
        pattern = FIELD_SCHEMAS[field]["pattern"]
        if not value:
            issues.append({"field": field, "problem": "required"})
        elif not isinstance(value, str) or not re.match(pattern, value):
            issues.append({"field": field, "problem": f"must match {pattern}"})
    check = check_request(report, {"score_type": entry["score_type"], "score_class": entry["score_class"],
                                   "params": arguments})
    issues += check["issues"]
    if issues:
        return {"verdict": "rejected", "issues": issues, "source_commit": check.get("source_commit")}
    params = check["score_resource"]["params"]
    if "inputs" in spec:
        # Send only what the user gave; the provisioner applies the platform defaults. Filling hidden defaults here
        # sent values such as node_security_group_id "" that score-api rightly rejects.
        params = {k: v for k, v in params.items() if k in spec["inputs"] and arguments.get(k) not in (None, "")}
    return {"verdict": "accepted", "score_type": entry["score_type"], "endpoint": spec["endpoint"],
            "workload": fields.get("workload"), "image": fields.get("image"),
            "params": params, "applied_defaults": check["applied_defaults"],
            "source_commit": check["source_commit"]}
